---
title: Sign our petition
author: ''
date: '2018-09-29'
slug: sign-our-petition
categories: []
tags: []
Description: ''
---

The Friends of Ryebank Fields are calling on neighbours and green space supporters to sign their [petition](https://you.38degrees.org.uk/petitions/give-ryebank-fields-back-to-the-people) calling for the land to be given back to the Council rather than used to develop houses.

We hope that you'll take a few moments to understand the reasons behind this petition and how it differs from other ideas being floated. The Friends of Ryebank Fields are a broad church and value the space for a huge variety of reasons. We do, however, gather around a few key beliefs:

- We value the habitats that wild spaces provide for a range of wildlife and recognise that we would all be poorer for the loss of the birds, insects and mammals that call our green spaces home.
- We believe that healthy and livable cities must include green spaces, acting as urban 'lungs' and offering free and peaceful spaces that benefit the mental and physical wellbeing of all.
- Having been gifted the site by the council for sport and recreation we do not believe that Manchester Metropolitan University have a moral right to benefit financially from the proposed housing development. The land belonged to Manchester citizens and should be returned to them for use as a public good.
- While we appreciate legitimate concerns both locally and nationally around the availability and affordability of housing we do not think that this area can support the demands that would be placed on local infrastructure by the addition of 70 executive homes. The impact on local traffic is particularly worrying especially given how close Ryebank Fields is to two local primary schools.

Please visit [38degrees.org](https://you.38degrees.org.uk/petitions/give-ryebank-fields-back-to-the-people) to add your name to the growing petition or join in the debate on our [Facebook](https://www.facebook.com/groups/FriendsofRyebank) and [Twitter](https://twitter.com/ryebankfields) pages.
